### ISSUE TITLE
Add section for scripts

### ISSUE THREAD

**Issue by dharmik2319** [edfloreshz/cosmic-project-collection#24]
As the title suggests, I wish to include my [script](https://github.com/dharmik2319/pywal-cosmic-term) here, but I did not find my script to fit in the existing categories.

**Comment by dharmik2319** [comment]
I have created #25. Please review.

**Comment by dharmik2319** [comment]
@edfloreshz any updates?

**Comment by edfloreshz** [comment]
I'll get to it this weekend 👍🏼
