### ISSUE TITLE
Update documentation stating for Rust Cosmic

### ISSUE THREAD

**Issue by flattery103** [edfloreshz/cosmic-project-collection#27]
Please update the documentation that things on this site are for the Rust Based Cosmic desktop currently in development and not the old Gnome-based with Extensions that current stable versions of Pop_OS! is using at the time of this writing.

I believe these are for the Rust Cosmic, but I can not find anything on this site to confirm that and since System76 calls both desktops Cosmic, it isn't necessarily obvious from anything I can see.

This would clear it up for anyone coming here.

**Comment by mmstick** [comment]
Applications for GNOME are just GNOME applications. It should be clear that COSMIC applications are built for COSMIC.
